const pfx = 'side_effects/app_store/';

/* ========= Actions ========= */

export const START_INIT_FETCH_FLOW = pfx + 'START_INIT_FETCH_FLOW';
export const INIT_FETCH_STARTED = pfx + 'INIT_FETCH_STARTED';
export const INIT_FETCH_SUCCESS = pfx + 'INIT_FETCH_SUCCESS';
export const INIT_FETCH_ERROR = pfx + 'INIT_FETCH_ERROR';

export const START_FETCHING_TOP_FREE_APPS_FLOW = pfx + 'START_FETCHING_TOP_FREE_APPS_FLOW';
export const FETCHING_TOP_FREE_APPS_STARTED = pfx + 'FETCHING_TOP_FREE_APPS_STARTED';
export const FETCHING_TOP_FREE_APPS_SUCCESS = pfx + 'FETCHING_TOP_FREE_APPS_SUCCESS';
export const FETCHING_TOP_FREE_APPS_ERROR = pfx + 'FETCHING_TOP_FREE_APPS_ERROR';

export const START_FETCHING_TOP_GROSSING_APPS_FLOW = pfx + 'START_FETCHING_TOP_GROSSING_APPS_FLOW';
export const FETCHING_TOP_GROSSING_APPS_STARTED = pfx + 'FETCHING_TOP_GROSSING_APPS_STARTED';
export const FETCHING_TOP_GROSSING_APPS_SUCCESS = pfx + 'FETCHING_TOP_GROSSING_APPS_SUCCESS';
export const FETCHING_TOP_GROSSING_APPS_ERROR = pfx + 'FETCHING_TOP_GROSSING_APPS_ERROR';

/* ========= Action Creators ========= */

export const startFetchingTopFreeAppsFlow = (limit = 100) => ({
    type: START_FETCHING_TOP_FREE_APPS_FLOW,
    limit
});

export default {
    START_INIT_FETCH_FLOW,
    INIT_FETCH_STARTED,
    INIT_FETCH_SUCCESS,
    INIT_FETCH_ERROR,

    START_FETCHING_TOP_FREE_APPS_FLOW,
    FETCHING_TOP_FREE_APPS_STARTED,
    FETCHING_TOP_FREE_APPS_SUCCESS,
    FETCHING_TOP_FREE_APPS_ERROR,

    START_FETCHING_TOP_GROSSING_APPS_FLOW,
    FETCHING_TOP_GROSSING_APPS_STARTED,
    FETCHING_TOP_GROSSING_APPS_SUCCESS,
    FETCHING_TOP_GROSSING_APPS_ERROR,

    startFetchingTopFreeAppsFlow,
};