/* The fields to be converted to or used */
export const appFields = {
    NAME: 'name',
    ICON: 'icon',
    ICON_HEIGHT: 'icon_height',
    ICON_2X: 'icon_2x',
    ICON_2X_HEIGHT: 'icon_2x_height',
    ICON_3X: 'icon_3x',
    ICON_3X_HEIGHT: 'icon_3x_height',
    SUMMARY: 'summary',
    PRICE_LABEL: 'price_label',
    PRICE_AMOUNT: 'price_amount',
    PRICE_CURRENCY: 'price_currency',
    CONTENT_TYPE_TERM: 'content_type_term',
    CONTENT_TYPE_LABEL: 'content_type_label',
    RIGHTS: 'rights',
    TITLE: 'title',
    LINK_REL: 'link_rel',
    LINK_TYPE: 'link_type',
    LINK_HREF: 'link_href',
    ID: 'id',
    BUNDLE_ID: 'bundle_id',
    ARTIST_LABEL: 'artist_label',
    ARTIST_HREF: 'artist_href',
    CATEGORY_ID: 'category_id',
    CATEGORY_TERM: 'category_term',
    CATEGORY_SCHEME: 'category_scheme',
    CATEGORY_LABEL: 'category_label',
    RELEASE_DATE_TIMESTAMP: 'release_date_timestamp',
    RELEASE_DATE_LABEL: 'release_date_label',
};

export const appStoreMetaFields = {
    STORE_NAME: 'store_name',
    STORE_URI: 'store_uri',
    LAST_UPDATE: 'last_update',
    RIGHTS: 'rights',
    TITLE: 'title',
    ICON: 'icon',
    LINK_REL: 'link_rel',
    LINK_TYPE: 'link_type',
    LINK_HREF: 'link_href',
}